name: API to CSV

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day
  workflow_dispatch:

jobs:
  call_api_and_generate_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Generate CSV Report Action
        uses: ./src/actions/apiToCsv.ts
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ent_name: 'avocado-corp'
          file_path: 'seats.csv'
